In [24]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [25]:
marathon_train.head()

,Name,Age,M/F,City,State,Country,5K,10K,15K,20K,...,25K,30K,35K,40K,Pace,Official Time,Overall,Gender,Division,Year
0,"Desisa, Lelisa",25,M,Ambo,NaN,ETH,883,1783,2697,3629,...,4567,5520,6479,7359,296,7757,1,1,1,2015
1,"Tsegay, Yemane Adhane",30,M,Addis Ababa,NaN,ETH,883,1783,2698,3628,...,4567,5519,6479,7362,298,7788,2,2,2,2015
2,"Chebet, Wilson",29,M,Marakwet,NaN,KEN,883,1783,2697,3629,...,4567,5520,6479,7381,299,7822,3,3,3,2015
3,"Kipyego, Bernard",28,M,Eldoret,NaN,KEN,883,1784,2701,3629,...,4567,5520,6483,7427,300,7847,4,4,4,2015
4,"Korir, Wesley",32,M,Kitale,NaN,KEN,883,1784,2698,3628,...,4567,5520,6479,7407,300,7849,5,5,5,2015

In [49]:
marathon_2015_2017 = pd.read_csv('./data/marathon_2015_2017.csv')

# training set
marathon_train = marathon_2015_2017[marathon_2015_2017['Year'] != 2017]
marathon_test = marathon_2015_2017[marathon_2015_2017['Year'] == 2017]

# record
record_train = pd.DataFrame(marathon_train, columns=['Age', 'M/F', 'Pace'])
record_test = pd.DataFrame(marathon_test, columns=['Age', 'M/F', 'Pace'])

def learning(age = 26, gender = 'M', rank = 1, step = 1, training = 100):
    model = tf.keras.models.Sequential()
    train = record_train[record_train['Age'] == age]
    train = train[train['M/F'] == gender].sort_values(['Pace'], ascending=[True])
    test = record_test[record_train['Age'] == age]
    test = test[test['M/F'] == gender].sort_values(['Pace'], ascending=[True])

    model.add(tf.keras.layers.Dense(1, input_shape=(3,)))
    
    sgd = tf.keras.optimizers.SGD(lr=step)
    
    model.compile(loss='categorical_hinge',
                 optimizer=sgd,
                 metrics=['accuracy'])
    model.summary()
    history = model.fit(np.array(train[0:2]), np.array(train[2]), epochs=step)
    for i in range(training):
        if i % 10 == 0:
            print('{}\t {}'.format(i, history.history['loss'][i]))
    
    #testing
    pace = model.predict(np.array([age, gender]))
    print('predict: {}, real: {}'.format(pace[rank], test[rank] - pace[rank]))

In [50]:
learning()

KeyError: 'pace'