In [4]:
import numpy as np

In [5]:
weight_vector = np.array([[1], [1], [1]])
x_vector = np.array([[3],[4],[5]])

In [6]:
weight_vector.T.dot(x_vector)

array([[12]])

In [7]:
import pandas as pd

In [8]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [9]:
df_data.values[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00, 2.400e+01])

In [10]:
df_data['weight_0'] = 1
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV,weight_0
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0,1
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6,1
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7,1
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4,1
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2,1

In [11]:
df_data=df_data.drop('MEDV',axis=1)
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,weight_0
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,1
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,1
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,1
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,1
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,1

In [12]:
df_data.as_matrix()

/home/lee/miniconda3/envs/tensorflow/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [13]:
df_data.shape # (row, column)

(506, 14)

In [14]:
df_matrix = df_data.as_matrix()
weight_vector = np.random.random_sample((14,1))

/home/lee/miniconda3/envs/tensorflow/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [16]:
df_matrix.dot(weight_vector)

array([[443.67931777],
       [399.60444069],
       [386.2468384 ],
       [362.02015238],
       [368.49905716],
       [369.59032277],
       [466.03606819],
       [485.83834169],
       [494.10709499],
       [477.33541946],
       [485.39426529],
       [475.05833217],
       [454.80977608],
       [457.14970254],
       [464.60002291],
       [454.39727248],
       [438.57666198],
       [468.75271132],
       [419.86034736],
       [460.98284629],
       [478.9415304 ],
       [472.83022829],
       [479.58434663],
       [483.53623313],
       [477.81063007],
       [450.59459798],
       [470.42115754],
       [453.59338776],
       [473.48102151],
       [467.62885117],
       [474.43017235],
       [473.60258988],
       [440.10961018],
       [470.56348642],
       [444.83403712],
       [431.9710242 ],
       [425.3329486 ],
       [419.5182495 ],
       [414.65531024],
       [404.94198163],
       [400.30269276],
       [351.25051439],
       [353.15429309],
       [357.38896862],
       [373.03453177],
       [372.2243659 ],
       [375.34106966],
       [402.46598526],
       [418.1959388 ],
       [390.9203625 ],
       [397.38625214],
       [401.43928599],
       [379.70578273],
       [382.4210621 ],
       [636.00581715],
       [389.19556783],
       [475.64802721],
       [425.14891875],
       [429.05947265],
       [440.07132743],
       [451.81211616],
       [460.56925993],
       [447.66150417],
       [439.20328979],
       [374.7150298 ],
       [485.75016886],
       [496.4295819 ],
       [477.70269006],
       [489.12609238],
       [483.81083134],
       [423.81069021],
       [429.6708465 ],
       [425.17323623],
       [422.6931258 ],
       [514.17564576],
       [530.91549092],
       [544.04367655],
       [533.01308512],
       [538.92294485],
       [530.50169783],
       [423.63364161],
       [441.70759247],
       [424.18484242],
       [429.79984381],
       [391.73923489],
       [391.39432178],
       [392.57919249],
       [393.45749167],
       [425.38692334],
       [414.77927869],
       [417.40077289],
       [420.78464302],
       [423.14702942],
       [410.56711127],
       [436.40285601],
       [409.20425589],
       [427.26120881],
       [425.75084649],
       [406.47193902],
       [421.13655941],
       [537.56419712],
       [532.42814528],
       [456.75896784],
       [544.21689543],
       [543.70238365],
       [550.28867855],
       [550.48685513],
       [541.44541751],
       [547.58488565],
       [546.80512114],
       [528.5315226 ],
       [582.50084198],
       [592.22361569],
       [594.88413252],
       [581.78925638],
       [576.81966103],
       [579.34657144],
       [582.80646459],
       [567.95019703],
       [576.8545988 ],
       [345.49334043],
       [348.94641982],
       [356.06583536],
       [362.12705358],
       [357.35713607],
       [353.19963774],
       [360.22799594],
       [600.05361617],
       [601.24089939],
       [602.42835997],
       [598.71761563],
       [599.30596391],
       [595.00185173],
       [597.70354567],
       [568.73594137],
       [602.16019482],
       [595.30200925],
       [599.71107061],
       [604.42724722],
       [603.47591291],
       [603.72852023],
       [618.57400262],
       [576.56847265],
       [576.79830754],
       [576.79947465],
       [518.0817802 ],
       [507.54908331],
       [574.38873564],
       [563.52260501],
       [557.35056504],
       [556.80415419],
       [548.95182196],
       [542.82693478],
       [530.353298  ],
       [543.73514002],
       [478.98054659],
       [483.81626081],
       [546.28703293],
       [546.44083974],
       [550.12217453],
       [538.65580676],
       [544.12078786],
       [552.32813207],
       [551.11188923],
       [559.19952196],
       [518.46669822],
       [547.55090183],
       [509.86890449],
       [535.05253617],
       [543.68939527],
       [535.05769764],
       [549.85033752],
       [458.6928505 ],
       [451.67810829],
       [444.54841395],
       [424.54818786],
       [435.84798831],
       [445.0077841 ],
       [444.62801631],
       [339.1929004 ],
       [352.33526614],
       [344.34849238],
       [353.61827243],
       [356.66057941],
       [359.43758676],
       [348.45347507],
       [335.80620082],
       [541.26705047],
       [531.78991308],
       [540.64809347],
       [528.98732921],
       [535.95659495],
       [532.65548709],
       [404.08586424],
       [403.21781518],
       [410.04604389],
       [481.53355548],
       [475.38025307],
       [484.35405904],
       [552.42143429],
       [548.42019556],
       [505.26036386],
       [491.89286688],
       [386.28924915],
       [384.34409087],
       [409.63786084],
       [423.41133096],
       [437.10219679],
       [426.04543071],
       [455.71054936],
       [446.0976657 ],
       [450.62120276],
       [426.86702764],
       [410.11632336],
       [406.97877426],
       [416.85415636],
       [423.32379912],
       [433.44555387],
       [445.19551048],
       [437.93182106],
       [466.88333626],
       [479.0563372 ],
       [462.38989593],
       [463.22071564],
       [455.71071264],
       [457.73435864],
       [459.4911218 ],
       [455.13744874],
       [425.95912762],
       [428.55497292],
       [456.17983538],
       [454.34098441],
       [453.27109891],
       [450.98648001],
       [447.96664498],
       [451.909162  ],
       [461.57716664],
       [455.53823494],
       [432.51121281],
       [445.30923855],
       [456.30760841],
       [462.84533959],
       [451.19887894],
       [426.14222113],
       [492.32502274],
       [498.78912713],
       [475.46705095],
       [492.68080286],
       [477.89425291],
       [466.04010503],
       [463.67570492],
       [454.93301674],
       [457.41904154],
       [461.41896008],
       [472.5063331 ],
       [469.44350875],
       [403.23765299],
       [421.30784916],
       [427.79276683],
       [429.31445754],
       [423.53593488],
       [423.9393846 ],
       [423.58646657],
       [431.14065649],
       [425.32922899],
       [415.40979659],
       [427.14345463],
       [413.26583019],
       [404.82628519],
       [383.29538662],
       [373.55220429],
       [358.48354166],
       [377.81655248],
       [373.50426094],
       [399.18586044],
       [403.1595098 ],
       [407.32122349],
       [397.04647208],
       [401.66562848],
       [355.29796925],
       [367.01959439],
       [356.90375131],
       [357.6751153 ],
       [354.4721347 ],
       [441.34631782],
       [449.29765413],
       [395.40730951],
       [445.16446249],
       [452.07966465],
       [436.83303108],
       [403.39602071],
       [403.57879394],
       [402.47147457],
       [416.27290843],
       [428.66368836],
       [420.59215339],
       [429.44532625],
       [441.06531106],
       [496.65384146],
       [492.81575814],
       [515.93807114],
       [477.79652758],
       [463.97098765],
       [462.29351276],
       [374.32759502],
       [383.06070482],
       [388.10145195],
       [388.23180787],
       [457.14172577],
       [458.49955923],
       [432.76011314],
       [444.52001594],
       [465.92832135],
       [458.88094147],
       [463.09584117],
       [460.83251197],
       [467.72496733],
       [462.0328822 ],
       [454.68468366],
       [453.53225788],
       [431.71957971],
       [432.35922899],
       [431.32087804],
       [444.21180635],
       [425.57140896],
       [412.71118467],
       [421.00439293],
       [433.23362515],
       [551.55883527],
       [543.61337062],
       [550.6632707 ],
       [449.07227778],
       [434.6413258 ],
       [364.14993917],
       [365.13740379],
       [365.91768414],
       [372.16383005],
       [378.61758296],
       [366.47470526],
       [371.40479238],
       [376.99174827],
       [433.15015486],
       [558.54572636],
       [529.75053221],
       [513.00006333],
       [492.38952752],
       [490.46025152],
       [508.62301301],
       [438.74412294],
       [480.70419843],
       [487.0933396 ],
       [556.88943684],
       [556.41657958],
       [357.22001122],
       [492.25039337],
       [487.41064745],
       [834.42937701],
       [826.73965601],
       [824.297301  ],
       [821.76081104],
       [816.81246269],
       [816.49909206],
       [822.87510758],
       [816.82090571],
       [806.22996069],
       [809.95136456],
       [806.7239207 ],
       [771.26959863],
       [817.9180146 ],
       [818.07543435],
       [822.86553031],
       [825.01343839],
       [814.23558009],
       [855.91123083],
       [865.68085516],
       [845.73441329],
       [838.78815751],
       [843.12552124],
       [857.45579335],
       [851.09632434],
       [913.86947423],
       [849.12550106],
       [845.05061382],
       [844.65312515],
       [828.41729554],
       [857.5306458 ],
       [863.61353763],
       [860.2899667 ],
       [849.65596475],
       [841.32590218],
       [835.71292749],
       [824.93419503],
       [847.85293505],
       [834.31722603],
       [840.81706211],
       [837.55271316],
       [836.6292077 ],
       [839.05745449],
       [879.29324409],
       [825.70768811],
       [863.25100096],
       [847.31669814],
       [837.43116702],
       [855.31187186],
       [855.60124923],
       [898.60729413],
       [848.6270381 ],
       [821.00295063],
       [823.20628621],
       [790.41806862],
       [771.89085411],
       [753.7181555 ],
       [767.54863138],
       [812.64131054],
       [811.5709664 ],
       [762.43016293],
       [746.98472555],
       [788.86201566],
       [806.52505672],
       [745.84908175],
       [819.6864342 ],
       [814.4345087 ],
       [807.09530609],
       [733.70806117],
       [723.90733757],
       [749.14383915],
       [726.52900784],
       [757.40912317],
       [753.80819917],
       [756.52715096],
       [751.93396964],
       [758.46141739],
       [743.97693821],
       [753.30561013],
       [763.79052179],
       [770.11503315],
       [746.75896143],
       [752.77145517],
       [767.58620468],
       [842.07118124],
       [851.73545137],
       [838.52466283],
       [835.83602142],
       [839.61319178],
       [806.78694637],
       [752.81295605],
       [815.666742  ],
       [836.60868512],
       [840.62608768],
       [815.52431081],
       [731.63501821],
       [825.57697223],
       [829.65437159],
       [833.51307986],
       [737.903102  ],
       [740.75159116],
       [731.5665139 ],
       [728.14841801],
       [798.64449691],
       [829.11819786],
       [794.28858824],
       [826.35981124],
       [827.78562761],
       [826.27780179],
       [820.44908022],
       [792.58443929],
       [730.90004738],
       [819.72733835],
       [827.25895573],
       [822.71110059],
       [828.13656432],
       [827.65511304],
       [820.66405835],
       [810.99603932],
       [826.38331423],
       [817.63666442],
       [834.30811453],
       [838.65487331],
       [835.95816072],
       [832.63327048],
       [816.44315332],
       [817.44426378],
       [818.48711843],
       [801.57829787],
       [798.27725908],
       [806.696877  ],
       [825.73739544],
       [808.32623014],
       [859.44890585],
       [853.6592962 ],
       [851.69315236],
       [861.0000414 ],
       [852.03297163],
       [533.80737353],
       [530.08097498],
       [526.4357637 ],
       [550.49240718],
       [543.63141472],
       [539.84191278],
       [544.98700754],
       [547.63861382],
       [424.14273623],
       [428.15139329],
       [431.79660571],
       [431.03222727],
       [429.17170475]])